Update Makefile

diff --git a/xtest/sdk/go/Makefile b/xtest/sdk/go/Makefile
--- a/xtest/sdk/go/Makefile
+++ b/xtest/sdk/go/Makefile
@@ -39,8 +39,8 @@ build:
 			echo "Error: Failed to copy otdfctl.sh for $$version"; \
 			exit 3; \
 		}; \
-		cp $(MAKEFILE_DIR)/otdfctl.yaml $(MAKEFILE_DIR)/dist/$$version/ || { \
-			echo "Error: Failed to copy otdfctl.yaml for $$version"; \
+		cp $(MAKEFILE_DIR)/opentdfctl.yaml $(MAKEFILE_DIR)/dist/$$version/ || { \
+			echo "Error: Failed to copy opentdfctl.yaml for $$version"; \
 			exit 3; \
 		}; \
 	done
