Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -29,5 +29,12 @@ jobs:
           pip install black pyright ruff
           ruff check
           black --check .
-          pyright .
         working-directory: xtest
+      - name: Run Pyright and summarize errors if any
+        run: |
+          set +e
+          OUTPUT=$(pyright 2>&1)
+          STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo -e "## type check error\n\`\`\`\n$OUTPUT\n\`\`\`" >> $GITHUB_STEP_SUMMARY
+          fi
