Update xtest workflow
This change improves the xtest workflow by splitting up tests by
platform-tag and sdk. This allows parallel test to run much faster.
This also adds comments from xtest to the PR, including links to
properly formatted test results.

diff --git a/.github/workflows/xtest.yml b/.github/workflows/xtest.yml
--- a/.github/workflows/xtest.yml
+++ b/.github/workflows/xtest.yml
@@ -68,12 +68,23 @@ jobs:
       go: ${{ steps.version-info.outputs.go-version-info }}
       java: ${{ steps.version-info.outputs.java-version-info }}
       js: ${{ steps.version-info.outputs.js-version-info }}
+      version-matrix: ${{ steps.version-matrix.outputs.sdks }}
     env:
       PLATFORM_REF: "${{ inputs.platform-ref || 'main lts' }}"
       JS_REF: "${{ inputs.js-ref }}"
       OTDFCTL_REF: "${{ inputs.otdfctl-ref }}"
       JAVA_REF: "${{ inputs.java-ref }}"
     steps:
+      - name: Define version matrix
+        id: version-matrix
+        run: |
+          if [[ "${FOCUS_SDK}" == "all" || "${FOCUS_SDK}" == "" ]]; then
+            echo 'sdks=["go", "js", "java"]' >> "$GITHUB_OUTPUT"
+          else
+            echo 'sdk=['"${FOCUS_SDK}"']' >> "$GITHUB_OUTPUT"
+          fi
+        env:
+          FOCUS_SDK: ${{ inputs.focus-sdk }}
       - name: Validate focus-sdk input
         if: ${{ inputs.focus-sdk != '' }}
         run: |-
@@ -112,6 +123,7 @@ jobs:
           python-version: "3.12"
       - run: |-
           pip install -r scripts/requirements.txt
+          pip install pytest-html
         working-directory: otdf-sdk/xtest/sdk
       - id: version-info
         uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
@@ -208,12 +220,15 @@ jobs:
     permissions:
       contents: read
       packages: read
+      checks: write # Needed to publish junit tests
+      pull-requests: write # Add comments to PRs
     env:
-      FOCUS_SDK: "${{ inputs.focus-sdk || 'all' }}"
+      FOCUS_SDK: ${{ matrix.sdk }}
     strategy:
       fail-fast: false
       matrix:
         platform-tag: ${{ fromJSON(needs.resolve-versions.outputs.platform-tag-list) }}
+        sdk: ${{ fromJSON(needs.resolve-versions.outputs.version-matrix) }}
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -241,7 +256,9 @@ jobs:
       - uses: bufbuild/buf-setup-action@2211e06e8cf26d628cda2eea15c95f8c42b080b3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
+
       - name: Set up JDK
+        if: matrix.sdk == 'java'
         uses: actions/setup-java@5896cecc08fd8a1fbdfaf517e29b571164b031f7
         with:
           java-version: "11"
@@ -249,12 +266,14 @@ jobs:
           server-id: github
 
       - name: Set up Node 22
+        if: matrix.sdk == 'js'
         uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
         with:
           node-version: "22.x"
 
       ######### CHECKOUT JS CLI #############
       - name: Configure js-sdk
+        if: matrix.sdk == 'js'
         uses: ./otdftests/xtest/setup-cli-tool
         with:
           path: otdftests/xtest/sdk
@@ -263,6 +282,7 @@ jobs:
 
       ######## SETUP THE JS CLI #############
       - name: build and setup the web-sdk cli
+        if: matrix.sdk == 'js'
         id: build-web-sdk
         run: |
           make
@@ -270,6 +290,7 @@ jobs:
 
       ######## CHECKOUT GO CLI #############
       - name: Configure otdfctl
+        if: matrix.sdk == 'go'
         id: configure-go
         uses: ./otdftests/xtest/setup-cli-tool
         with:
@@ -278,6 +299,7 @@ jobs:
           version-info: "${{ needs.resolve-versions.outputs.go }}"
 
       - name: Resolve otdfctl heads
+        if: matrix.sdk == 'go'
         id: resolve-otdfctl-heads
         run: |-
           echo "OTDFCTL_HEADS=$OTDFCTL_HEADS" >> "$GITHUB_ENV"
@@ -285,7 +307,7 @@ jobs:
           OTDFCTL_HEADS: ${{ steps.configure-go.outputs.heads }}
 
       - name: Replace otdfctl go.mod packages, but only at head version of platform
-        if: env.FOCUS_SDK == 'go' && contains(fromJSON(needs.resolve-versions.outputs.heads), matrix.platform-tag)
+        if: matrix.sdk == 'go' && env.FOCUS_SDK == 'go' && contains(fromJSON(needs.resolve-versions.outputs.heads), matrix.platform-tag)
         run: |-
           echo "Replacing go.mod packages..."
           PLATFORM_DIR_ABS="$(pwd)/${{ steps.run-platform.outputs.platform-working-dir }}"
@@ -303,6 +325,7 @@ jobs:
 
       ######## SETUP THE GO CLI #############
       - name: Prepare go cli
+        if: matrix.sdk == 'go'
         run: |-
           make
         working-directory: otdftests/xtest/sdk/go
@@ -310,6 +333,7 @@ jobs:
       ####### CHECKOUT JAVA SDK ##############
 
       - name: Configure java-sdk
+        if: matrix.sdk == 'java'
         uses: ./otdftests/xtest/setup-cli-tool
         with:
           path: otdftests/xtest/sdk
@@ -318,7 +342,7 @@ jobs:
 
       - name: pre-release protocol buffers for java-sdk
         if: |
-          contains('["go", "java"]', env.FOCUS_SDK) && contains(fromJSON(needs.resolve-versions.outputs.heads), matrix.platform-tag)
+          matrix.sdk == 'java' && contains('["go", "java"]', env.FOCUS_SDK) && contains(fromJSON(needs.resolve-versions.outputs.heads), matrix.platform-tag)
         run: |-
           echo "Replacing .env files for java-sdk..."
           echo "Platform tag: $platform_tag"
@@ -338,6 +362,7 @@ jobs:
 
       ####### SETUP JAVA CLI ##############
       - name: Prepare java cli
+        if: matrix.sdk == 'java'
         run: |
           make
         env:
@@ -366,36 +391,33 @@ jobs:
       - name: Install test dependencies
         run: |-
           pip install -r requirements.txt
+          pip install pytest-html
         working-directory: otdftests/xtest
       - name: Validate xtest helper library (tests of the test harness and its utilities)
         if: ${{ !inputs }}
         run: |-
-          pytest test_nano.py test_self.py
+          pytest --html=test-results/helper-${FOCUS_SDK}-${PLATFORM_TAG}.html --self-contained-html test_nano.py test_self.py
         working-directory: otdftests/xtest
+        env:
+          PLATFORM_TAG: ${{ matrix.platform-tag }}
 
       ######## RUN THE TESTS #############
       - name: Run legacy decryption tests
         run: |-
-          pytest -ra -v --focus "$FOCUS_SDK" test_legacy.py
+          pytest --html=test-results/sdk-${FOCUS_SDK}-${PLATFORM_TAG}.html --self-contained-html -ra -v --focus "$FOCUS_SDK" test_legacy.py
         working-directory: otdftests/xtest
         env:
           PLATFORM_DIR: "../../${{ steps.run-platform.outputs.platform-working-dir }}"
-      - name: Run all standard xtests
-        if: ${{ env.FOCUS_SDK == 'all' }}
-        run: |-
-          pytest -ra -v test_tdfs.py test_policytypes.py
-        working-directory: otdftests/xtest
-        env:
-          PLATFORM_DIR: "../../${{ steps.run-platform.outputs.platform-working-dir }}"
-          SCHEMA_FILE: "manifest.schema.json"
+          PLATFORM_TAG: ${{ matrix.platform-tag }}
       - name: Run xtests focusing on a specific SDK
         if: ${{ env.FOCUS_SDK != 'all' }}
         run: |-
-          pytest -ra -v --focus "$FOCUS_SDK" test_tdfs.py test_policytypes.py
+          pytest --html=test-results/sdk-${FOCUS_SDK}-${PLATFORM_TAG}.html  --self-contained-html -ra -v --focus "$FOCUS_SDK" test_tdfs.py test_policytypes.py
         working-directory: otdftests/xtest
         env:
           PLATFORM_DIR: "../../${{ steps.run-platform.outputs.platform-working-dir }}"
           SCHEMA_FILE: "manifest.schema.json"
+          PLATFORM_TAG: ${{ matrix.platform-tag }}
 
       ######## ATTRIBUTE BASED CONFIGURATION #############
 
@@ -450,7 +472,43 @@ jobs:
       - name: Run attribute based configuration tests
         if: ${{ steps.multikas.outputs.supported == 'true' }}
         run: |-
-          pytest -ra -v --focus "$FOCUS_SDK" test_abac.py
+          pytest --html=test-results/attributes-${FOCUS_SDK}-${PLATFORM_TAG}.html --self-contained-html -ra -v --focus "$FOCUS_SDK" test_abac.py
         working-directory: otdftests/xtest
         env:
           PLATFORM_DIR: "../../${{ steps.run-platform.outputs.platform-working-dir }}"
+          PLATFORM_TAG: ${{ matrix.platform-tag }}
+
+      - name: Upload artifact
+        uses: actions/upload-artifact@v4
+        id: upload-artifact
+        if: success() || failure()
+        with:
+          name: ${{ job.status == 'success' && '✅' || job.status == 'failure' && '❌' }} ${{ matrix.sdk }}-${{matrix.platform-tag}}
+          path: otdftests/xtest/test-results/*.html
+
+  publish-results:
+    runs-on: ubuntu-latest
+    needs: cross-client-test
+    if: always() # Always try to publish results, even if tests fail
+    permissions:
+      pull-requests: write # Add comments to PRs
+    steps:
+      - id: comment-artifact-list
+        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea #v7.0.1
+        with:
+          script: |
+            const { owner, repo} = context.repo;
+            const runId = context.runId;
+            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
+              owner,
+              repo,
+              run_id: runId,
+            })
+            const results = artifacts.data.artifacts.map(({ name, id }) => `[${name}](https://github.com/${owner}/${repo}/actions/runs/${runId}/artifacts/${id})`).join('\n');
+            const md = `## X-Test Failure Results\n${results}`
+            await github.rest.issues.createComment({
+              owner,
+              repo,
+              issue_number: context.issue.number,
+              body: md,
+            })
