chore(xtest): Adds skew testing with multiple versions of clients (#265)
Tests one or up to three (head, last tagged service, lts (0.4.26, which was included in dsp-bundle 2.0.2) platform versions against the main (and possibly LTS) versions of the clients, and supports clients triggering the workflow with up to four test versions as well.

diff --git a/.github/workflows/xtest.yml b/.github/workflows/xtest.yml
--- a/.github/workflows/xtest.yml
+++ b/.github/workflows/xtest.yml
@@ -37,41 +37,110 @@ on:
       otdfctl-ref:
         required: false
         type: string
-        default: main
+        default: main latest
       js-ref:
         required: false
         type: string
-        default: main
+        default: main latest
       java-ref:
         required: false
         type: string
-        default: main
+        default: main latest
       focus-sdk:
         required: false
         type: string
         default: all
   schedule:
     - cron: "30 6 * * *"
+    - cron: "0 18 * * 0"
 jobs:
+  resolve-versions:
+    timeout-minutes: 10
+    runs-on: ubuntu-latest
+    permissions: 
+      contents: read
+    outputs:
+      platform-tag-to-sha: ${{ steps.platform-version-info.outputs.platform-tag-to-sha }}
+      tag-list: ${{ steps.platform-version-info.outputs.tag-list }}
+    steps:
+      - name: Validate focus-sdk input
+        if : ${{ inputs.focus-sdk != '' }}
+        run: |-
+          if [[ ! "all go java js" =~ (^|[[:space:]])${{ inputs.focus-sdk }}($|[[:space:]]) ]]; then
+            echo "Invalid focus-sdk input: ${{ inputs.focus-sdk }}. Must be one of: all, go, java, js." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+      - uses: actions/checkout@v4
+        with:
+          path: otdf-sdk
+          sparse-checkout: xtest/sdk
+      - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
+        with:
+          python-version: "3.12"
+      - run: |-
+          pip install -r scripts/requirements.txt
+        working-directory: otdf-sdk/xtest/sdk
+      - if: github.event_name != 'cron' || github.event.schedule != '0 18 * * 0'
+        run: |-
+          echo "PLATFORM_REF=${{ inputs.platform-ref || 'main lts' }}" >> $GITHUB_ENV
+      - if: github.event_name == 'cron' && github.event.schedule == '0 18 * * 0'
+        # Only run the full platform matrix on sundays at 6pm UTC
+        run: |-
+          echo "PLATFORM_REF=${{ github.event.inputs.platform-ref || 'main latest lts' }}" >> $GITHUB_ENV
+      - id: platform-version-info
+        run: |-
+          version_info=$(./scripts/resolve-version.py platform $PLATFORM_REF)
+          echo "tag-list=$(echo $version_info | jq -rc '[.[].tag]')" >> $GITHUB_OUTPUT
+          echo "platform-tag-to-sha=$(echo $version_info | jq -rc 'map({(.tag): .sha}) | add')" >> $GITHUB_OUTPUT
+
+          echo "### Platform Versions under Test" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "| Tag | SHA | Alias | Error |" >> $GITHUB_STEP_SUMMARY
+          echo "| --- | --- | ----- | ----- |" >> $GITHUB_STEP_SUMMARY
+          echo "$version_info" | jq -rc '.[] | "| \(.tag) | \(.sha) | \(.alias // "N/A") | \(.err // "N/A") |"' >> $GITHUB_STEP_SUMMARY
+
+          # Check for errors in the version_info
+          error_count=$(echo "$version_info" | jq '[.[] | select(.err != null)] | length')
+          if [ "$error_count" -gt 0 ]; then
+            echo "Errors detected in version resolution. Failing the run." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+        working-directory: otdf-sdk/xtest/sdk
+    
+      
   cross-client-test:
     timeout-minutes: 60
     runs-on: ubuntu-latest
+    needs: resolve-versions
     permissions:
       contents: read
       packages: read
     env:
-      PLATFORM_REF: "${{ inputs.platform-ref || 'main' }}"
-      JS_REF: "${{ inputs.js-ref || 'main' }}"
-      OTDFCTL_REF: "${{ inputs.otdfctl-ref || 'main' }}"
-      JAVA_REF: "${{ inputs.java-ref || 'main' }}"
       FOCUS_SDK: "${{ inputs.focus-sdk || 'all' }}"
+    strategy:
+      fail-fast: false
+      matrix:
+        platform-tag: ${{ fromJSON(needs.resolve-versions.outputs.tag-list) }}
     steps:
+      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+        with:
+          repository: opentdf/tests
+          path: otdftests # use different name bc other repos might have tests directories
+
+      ######## CHECKOUT WEB SDK #############
+      - name: Configure web SDK tools
+        uses: ./otdftests/xtest/setup-cli-tool
+        with:
+          path: otdftests/xtest/sdk
+          sdk: js
+          version: "${{ inputs.js-ref || 'main' }}"
+
       ######## SPIN UP PLATFORM BACKEND #############
       - name: Check out and start up platform with deps/containers
         id: run-platform
         uses: opentdf/platform/test/start-up-with-containers@main
         with:
-          platform-ref: ${{ env.PLATFORM_REF }}
+          platform-ref: ${{ fromJSON(needs.resolve-versions.outputs.platform-tag-to-sha)[matrix.platform-tag] }}
           ec-tdf-enabled: true
           extra-keys: >- 
             [{
@@ -81,10 +150,6 @@ jobs:
               "cert": "-----BEGIN CERTIFICATE-----\nMIIC/TCCAeWgAwIBAgIUDiCm76cjcg4Wd862cEzTzLqSzFswDQYJKoZIhvcNAQEL\nBQAwDjEMMAoGA1UEAwwDa2FzMB4XDTI0MTIxODIwMzUxNFoXDTI1MTIxODIwMzUx\nNFowDjEMMAoGA1UEAwwDa2FzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC\nAQEA8QF4D9ko0T4SnjtTnS3KO87FPrjJ70BZ063NFvHkP71Boz/BzQAQN5ClHiWV\nBm+JchObutrAag/lWjlodLSEQiBD0Qv7Rd4UxOU3gySyYmPTd0eT/To1rhXsJ0BV\nyH0z6pq58taWKMH5HZ28QUs2/8U6ZOivss5Mq2XVtSb2HVv9QgRqaO6rX8X5Udws\ntd1deWA7lUw9qx1EozNnmFFPm+By6B7ymfO8tfJ8GjjDjDKm76eMRaMXJKBP15Lm\nh8h9VFiPR6gshQa4fn9uDjzD9Dd6jArHlyXNgkwRkl+IynQdFhqjqWXQcSlpSsSx\npSgHvSqNXmM1B3YYTaQUZlOB8wIDAQABo1MwUTAdBgNVHQ4EFgQUVl6EWRsZE5kf\nXR6EC9LDStsR1howHwYDVR0jBBgwFoAUVl6EWRsZE5kfXR6EC9LDStsR1howDwYD\nVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAJysUw1bQkm+UdIWubPVo\nh/h1YoSHMEmwtphLflMDiJvm1GIjFM5zVgnpmkiI9DVCAs8vyhHe+UVCgiCAMqU9\nuu1jYxXY54v8nx+Ps3X1snylIs82JHKXT1AJaXECSi0DwIuF3hIyPUJpK9AJ/PqC\nOvhq3sMX5p0D3bmk8518rRwkSZ2a7jn5qvLa6P0g4Ph32j5UdRmgvsgh/jJk7PkK\nHuf86yZ4KbkgU6kMs4rTOLNIBmMJlm7R9xrGMVwK8X/NPZWV4fBNQZPIJw7svNzo\npe60OK4cT0G0/LHEOGxCLpmxjq2+xedKkrmq6PrRZquL386RyjkCZh6F5AWJCqB9\n4g==\n-----END CERTIFICATE-----\n"
             }]
 
-      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-        with:
-          repository: opentdf/tests
-          path: otdftests # use different name bc other repos might have tests directories
       - name: Set up Python 3.12
         uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b
         with:
@@ -99,18 +164,10 @@ jobs:
           distribution: "adopt"
           server-id: github
 
-      ######## CHECKOUT WEB SDK #############
-      - name: Check out web-sdk
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
-        with:
-          repository: opentdf/web-sdk
-          path: otdftests/xtest/sdk/js/src/main
-          ref: ${{ env.JS_REF }}
       - name: Set up Node 22
         uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
         with:
           node-version: "22.x"
-          cache-dependency-path: web-sdk/lib/package-lock.json web-sdk/cli/package-lock.json
 
       ######## SETUP THE JS CLI #############
       - name: build and setup the web-sdk cli
@@ -120,14 +177,15 @@ jobs:
         working-directory: otdftests/xtest/sdk/js
 
       ######## CHECKOUT GO CLI #############
-      - name: Check out otdfctl
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - name: Configure otdfctl
+        uses: ./otdftests/xtest/setup-cli-tool
         with:
-          repository: opentdf/otdfctl
-          path: otdftests/xtest/sdk/go/src/main
-          ref: ${{ env.OTDFCTL_REF }}
+          path: otdftests/xtest/sdk
+          sdk: go
+          version: "${{ inputs.otdfctl-ref || 'main' }}"
 
       - name: Replace otdfctl go.mod packages
+        if: env.FOCUS_SDK == 'go'
         run: |-
           echo "Replacing go.mod packages..."
           PLATFORM_DIR_ABS="$(pwd)/${{ steps.run-platform.outputs.platform-working-dir }}"
@@ -148,15 +206,14 @@ jobs:
 
       ####### CHECKOUT JAVA SDK ##############
 
-      - name: Check out java-sdk
-        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
+      - name: Configure java-sdk
+        uses: ./otdftests/xtest/setup-cli-tool
         with:
-          repository: opentdf/java-sdk
-          path: otdftests/xtest/sdk/java/src/main
-          ref: ${{ env.JAVA_REF }}
+          path: otdftests/xtest/sdk
+          sdk: java
+          version: "${{ inputs.java-ref || 'main' }}"
 
       ####### SETUP JAVA CLI ##############
-
       - name: Prepare java cli
         run: |
           make
@@ -165,7 +222,24 @@ jobs:
           BUF_INPUT_HTTPS_PASSWORD: ${{ secrets.PERSONAL_ACCESS_TOKEN_OPENTDF }}
         working-directory: otdftests/xtest/sdk/java
 
-      ######## RUN THE TESTS #############
+      ######## Configure test environment #############
+      - name: Lookup current platform version
+        id: platform-version
+        run: |-
+          if ! go run ./service version; then
+            # NOTE: the version command was added in 0.4.37
+            echo "Error: Unable to get platform version; defaulting to tag: [$PLATFORM_TAG]"
+            echo "PLATFORM_VERSION=$PLATFORM_TAG" >> $GITHUB_ENV
+            exit
+          fi
+          # Older version commands output version to stderr; newer versions output to stdout
+          PLATFORM_VERSION=$(go run ./service version 2>&1)
+          echo "PLATFORM_VERSION=$PLATFORM_VERSION" >> $GITHUB_ENV
+          echo "## Platform version output: [$PLATFORM_VERSION]"
+        working-directory: ${{ steps.run-platform.outputs.platform-working-dir }}
+        env:
+          PLATFORM_TAG: ${{ matrix.platform-tag }}
+
       - name: Install test dependencies
         run: |-
           pip install -r requirements.txt
@@ -175,11 +249,13 @@ jobs:
         run: |-
           curl -L -o manifest.schema.json https://raw.githubusercontent.com/opentdf/platform/main/sdk/schema/manifest.schema.json
         working-directory: otdftests/xtest
-      - name: Validate xtests
+      - name: Validate xtest helper library (tests of the test harness and its utilities)
         if: ${{ !inputs }}
         run: |-
           pytest test_nano.py test_self.py
         working-directory: otdftests/xtest
+
+      ######## RUN THE TESTS #############
       - name: Run legacy decryption tests
         run: |-
           pytest -v  --focus "$FOCUS_SDK" test_legacy.py
@@ -204,7 +280,25 @@ jobs:
           SCHEMA_FILE: 'manifest.schema.json'
 
       ######## ATTRIBUTE BASED CONFIGURATION #############
+
+      - name: Does platform support multikas?
+        id: multikas
+        run: |-
+          if [[ $PLATFORM_TAG == main ]]; then
+            echo "Main supports multikas"
+            echo "supported=true" >> "$GITHUB_OUTPUT"
+          elif [[ $PLATFORM_VERSION =~ ^0\.[5-9]\.[0-9]+$ ]]; then
+            echo "Selected version [$PLATFORM_VERSION] supports multikas"
+            echo "supported=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "At tag [$PLATFORM_TAG], [$PLATFORM_VERSION] probably does not support multikas"
+            echo "supported=false" >> "$GITHUB_OUTPUT"
+          fi
+        env:
+          PLATFORM_TAG: ${{ matrix.platform-tag }}
+
       - name: Start additional kas
+        if: ${{ steps.multikas.outputs.supported == 'true' }}
         uses: opentdf/platform/test/start-additional-kas@main
         with:
           ec-tdf-enabled: true
@@ -212,6 +306,7 @@ jobs:
           kas-name: alpha
 
       - name: Start additional kas
+        if: ${{ steps.multikas.outputs.supported == 'true' }}
         uses: opentdf/platform/test/start-additional-kas@main
         with:
           ec-tdf-enabled: true
@@ -219,6 +314,7 @@ jobs:
           kas-name: beta
       
       - name: Start additional kas
+        if: ${{ steps.multikas.outputs.supported == 'true' }}
         uses: opentdf/platform/test/start-additional-kas@main
         with:
           ec-tdf-enabled: true
@@ -226,6 +322,7 @@ jobs:
           kas-name: gamma
 
       - name: Start additional kas
+        if: ${{ steps.multikas.outputs.supported == 'true' }}
         uses: opentdf/platform/test/start-additional-kas@main
         with:
           ec-tdf-enabled: true
@@ -233,6 +330,7 @@ jobs:
           kas-name: delta
 
       - name: Run attribute based configuration tests
+        if: ${{ steps.multikas.outputs.supported == 'true' }}
         run: |-
           pytest test_abac.py
         working-directory: otdftests/xtest
